//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingsman20.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string FLP { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
    }
}
